#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : x264
Version  : 1
Release  : 1
URL      : https://code.videolan.org/videolan/x264/-/archive/stable/x264-stable.tar.gz
Source0  : https://code.videolan.org/videolan/x264/-/archive/stable/x264-stable.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: x264-bin = %{version}-%{release}
Requires: x264-lib = %{version}-%{release}
BuildRequires : nasm
BuildRequires : yasm

%description
No detailed description available

%package bin
Summary: bin components for the x264 package.
Group: Binaries

%description bin
bin components for the x264 package.


%package dev
Summary: dev components for the x264 package.
Group: Development
Requires: x264-lib = %{version}-%{release}
Requires: x264-bin = %{version}-%{release}
Provides: x264-devel = %{version}-%{release}
Requires: x264 = %{version}-%{release}

%description dev
dev components for the x264 package.


%package lib
Summary: lib components for the x264 package.
Group: Libraries

%description lib
lib components for the x264 package.


%prep
%setup -q -n x264-stable
cd %{_builddir}/x264-stable

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586632162
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --enable-shared
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1586632162
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/x264

%files dev
%defattr(-,root,root,-)
/usr/include/x264.h
/usr/include/x264_config.h
/usr/lib64/libx264.so
/usr/lib64/pkgconfig/x264.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libx264.so.159
